### ISSUE TITLE
Unable to install in Windows environment

### ISSUE THREAD

**Issue by cimka** [paulross/TotalDepth#10]
Hi there,

I am trying to install TotalDepth on a Windows environment and it fails on this line due to CFLAGS not present in Windows.
https://github.com/paulross/TotalDepth/blob/64f4a1fc497994d18bc3a903f8013adf3db8c16a/setup.py#L88

I do not know if there is more issues regarding this yet.

**Comment by paulross** [comment]
Hi,

Thanks for raising this. If you remove that line does it build OK on Windows (I don't have a Windows environment available to me to test. this)? If so I'll make that line conditional.

**Comment by cimka** [comment]
Hi Paul,
Sorry for the late reply.
I had some other tasks I needed to fix before I could look into this one.
It looks like installing on Windows works with correcting this like.
I will submit a PR later. Also had issue with some linux environments with v0.3.
Will try to investigate and include that one also into same PR.

**Comment by paulross** [comment]
OK thanks, I'll keep an eye out for the PR.

**Comment by cimka** [comment]
Hi Paul,

It took some investigations to find out the linux one.
Here is the PR:
https://github.com/paulross/TotalDepth/pull/11

I found some issue related to running this on windows just for info.
I prioritized to fix installation first. Ill check it out at some point.

**Comment by mystardustcaptain** [comment]
Any update on this PR?

**Comment by paulross** [comment]
Should now be fixed with v0.3.1

Let me know if not!

**Comment by paulross** [comment]
Closing as no further feedback.
