### ISSUE TITLE
Do you have an example of using pickle with a lis index?

### ISSUE THREAD

**Issue by jis260** [paulross/TotalDepth#28]
I have been trying to use Python pickling with the output from the LIS Indexer, e.g.

`
import pickle
from TotalDepth.LIS.core import File
from TotalDepth.LIS.core import FileIndexer
lisFile = File.FileRead('file.lis', keepGoing=True)
lisIndex = FileIndexer.FileIndex(lisFile)

pickled = pickle.dumps(lisIndex) # pickle the index
lisIndexLoad = pickle.loads(pickled) # this gives an error, __new__() takes 2 positional arguments but 5 were given
`

I am not very familiar with "Pickling" in Python, but I was hoping this would provide a method to store in lisIndex and reuse it? However, I have not seen an example of this in the documentation so perhaps it is not possible?

**Comment by paulross** [comment]
Thanks for that, yes that's a bug. I have made release 0.3.5 that fixes it [here](https://pypi.org/project/TotalDepth/#files).

**Comment by jis260** [comment]
Thank you very much. 

I tested the "lisIndex" before and after pickling with,
```
for aLr in lisIndex.genAll():
     print(aLr)

for aLr in lisIndexLoad.genAll():
     print(aLr)
```
and it is the same output. So I can confirm the fix.
