### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by AW313** [paulross/TotalDepth#37]
Hi,
I'm getting an error on the pip install...

using windows and VSC, versions;
VSC 1.66.2
python 3.9.7. 

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for TotalDepth

**Comment by paulross** [comment]
I'm afraid I don't have access to a Windows environment so I can not solve this directly.
It looks like your tool chain is rather old, as the error message suggests you need Microsoft Visual C++ 14.0 which was released back on 2015-07-20.

Some links that might help you solve this problem:
https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required
https://docs.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html

Good luck!
