### ISSUE TITLE
Installation problem with pip

### ISSUE THREAD

**Issue by erlendviggen** [paulross/TotalDepth#5]
I am installing TotalDepth for the first time, and I tried using pip as recommended by the documentation. Specifically, I'm trying to install on top of a Python 3.6 Anaconda distribution on macOS 10.13.4. However, this is giving me the following error:
```
$ pip install totaldepth

Collecting totaldepth
  Using cached TotalDepth-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0k/6fvjhp7x2659gf4_pbq0zkj40000gp/T/pip-install-3_oz2lvj/totaldepth/setup.py", line 125, in <module>
        ext_modules = cythonize("src/TotalDepth/LIS/core/*.pyx"),
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'src/TotalDepth/LIS/core/*.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0k/6fvjhp7x2659gf4_pbq0zkj40000gp/T/pip-install-3_oz2lvj/totaldepth/
```
Indeed, the directory `src/TotalDepth/LIS/core/` does not contain any .pyx files in the PyPi version.

**Comment by erlendviggen** [comment]
The alternate installation method from the documentation seems to work perfectly, though, with almost all of the tests passing:

`======= 12 failed, 1608 passed, 3 xfailed, 1 warnings in 298.97 seconds ========`

The failed ones seem to be some hash comparisons related to the HTML utilities, so I'm not too worried about those.

**Comment by paulross** [comment]
Hmm, yes the two .pyx files appear to be missing from the pip distribution. I'll look into this. I'm glad you got it working anyway, presumably by cloning the GitHub repo.

Looks like 1608 test passing is about right and yes some of the HTML comparisons are a bit fragile so you can ignore them.

**Comment by everhappy388** [comment]
I encountered the same problem during installing. Have the missing files been added yet? Can you show me how you installed using the alternative method? I am a novice in python. Thanks.

**Comment by erlendviggen** [comment]
I followed the ["From sources"](https://totaldepth.readthedocs.io/en/latest/installation.html#from-sources) section in the TotalDepth manual, more or less. The only difference is that I used the Anaconda Python distribution's way of creating virtual environments and installing packages.

(By the way, virtual environments are basically separate Python installations that you can switch between at will. This means that you can install exactly the packages that TotalDepth needs, without fear that it will in any way conflict with any other programs that require different versions of the same packages or anything like that.)

I don't really know if using Anaconda for the virtual environment is better than using plain Python (I'm only an intermediate Python user myself), but with Anaconda, the code in the cell under "First make a virtual environment" would be:
```
conda create --name TotalDepth python=3.6 pip
source activate TotalDepth
```
You'll need to use the last line as well whenever you want to switch to the TotalDepth virtual environment. You could also install packages using Anaconda's package manager as an alternative to pip, which would be:
```
conda install numpy
conda install Cython
```

As I said, I don't know if using Anaconda is really that helpful at all; I guess the installation should go ahead just as smoothly without it if you just follow the instructions in the manual directly.

**Comment by paulross** [comment]
Hopefully fixed now as the .pyx files are now shipped with the PyPi source distribution. I took the opportunity to bump the version to 0.2.1

I should include a section in the documentation about installing with Anaconda.

Thanks for reporting this!

**Comment by erlendviggen** [comment]
Happy to help! I can confirm that installing by pip works perfectly now. Thanks!
